const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('livemapApi', {
  getOreData: () => ipcRenderer.invoke('get-ore-data'),
  getUiSettings: () => ipcRenderer.invoke('ui-settings-get'),
  setUiSettings: (patch) => ipcRenderer.invoke('ui-settings-set', patch),
  onPlayerPosition: (callback) => ipcRenderer.on('player-position', (_event, data) => callback(data)),
  onPlayerError: (callback) => ipcRenderer.on('player-error', (_event, data) => callback(data)),
  onInventoryUpdate: (callback) => ipcRenderer.on('inventory-update', (_event, data) => callback(data)),
  onInventoryError: (callback) => ipcRenderer.on('inventory-error', (_event, data) => callback(data)),
  getPlayerPositionLock: () => ipcRenderer.invoke('player-lock-get'),
  setPlayerPositionLock: (payload) => ipcRenderer.invoke('player-lock-set', payload),
  openTutorial: () => ipcRenderer.invoke('tutorial-open'),
  closeTutorial: () => ipcRenderer.invoke('tutorial-close'),
  updateTutorialStep: (payload) => ipcRenderer.invoke('tutorial-step-update', payload),
  getDisplayWorkArea: () => ipcRenderer.invoke('display-workarea-get'),
  minimizeWindow: () => ipcRenderer.invoke('window-minimize'),
  closeWindow: () => ipcRenderer.invoke('window-close'),
  closeWindowSkipUpdate: () => ipcRenderer.invoke('window-close-skip-update'),
  getWindowOpacity: () => ipcRenderer.invoke('window-get-opacity'),
  setWindowOpacity: (value) => ipcRenderer.invoke('window-set-opacity', value),
  getWindowBounds: () => ipcRenderer.invoke('window-get-bounds'),
  setWindowBounds: (bounds) => ipcRenderer.invoke('window-set-bounds', bounds),
  openRoutePlanner: () => ipcRenderer.invoke('route-planner-open'),
  closeRoutePlanner: () => ipcRenderer.invoke('route-planner-close'),
  getRouteState: () => ipcRenderer.invoke('route-state-get'),
  previewRoute: (route) => ipcRenderer.invoke('route-preview-set', route),
  startRoute: (route) => ipcRenderer.invoke('route-start-set', route),
  abortRoute: () => ipcRenderer.invoke('route-abort'),
  toggleRoutePause: () => ipcRenderer.invoke('route-pause-toggle'),
  getUpdaterState: () => ipcRenderer.invoke('updater-state-get'),
  installUpdateNow: () => ipcRenderer.invoke('updater-install-now'),
  onRoutePreview: (callback) => ipcRenderer.on('route-preview', (_event, data) => callback(data)),
  onRouteStart: (callback) => ipcRenderer.on('route-start', (_event, data) => callback(data)),
  onRouteAbort: (callback) => ipcRenderer.on('route-abort', () => callback()),
  onRouteState: (callback) => ipcRenderer.on('route-state', (_event, data) => callback(data)),
  onUpdaterState: (callback) => ipcRenderer.on('updater-state', (_event, data) => callback(data)),
  onTutorialStep: (callback) => ipcRenderer.on('tutorial-step', (_event, data) => callback(data)),
  onTutorialAction: (callback) => ipcRenderer.on('tutorial-action', (_event, data) => callback(data)),
  requestTutorialAction: (action) => ipcRenderer.invoke('tutorial-action', action),
});
